FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN npm install
RUN npm run db:generate

EXPOSE 8000

CMD [ "npm", "run" ,"start:backend" ]